### ISSUE TITLE
benchmark suite

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-metadata#12]
Would be nice to have a small benchmark suite ready to be used so we can track performance of the server throughout progress of the project.

Todo:
- select REST API benchmarking tool
- write a bunch of benchmark config
- allow to run benchmark from Makefile in one command

**Comment by lafont-e** [comment]
(https://github.com/zero-os/0-metadata/pull/16) 
is a benchmark script, review it and tell me if you have suggestions
