### ISSUE TITLE
need docs and example

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-metadata#17]
This project really need docs & example

**Comment by iwanbk** [comment]
I got this error
```python
...
 File "/home/ibk/work/incubaid/0-metadata/server/dir_api.py", line 19, in listDir
    return handlers.listDirHandler()
  File "/home/ibk/work/incubaid/0-metadata/server/handlers/listDirHandler.py", line 9, in listDirHandler
    redis = current_app.config['redis']
KeyError: 'redis'
```
Will be great if there is doc about server config

**Comment by iwanbk** [comment]
also need more description about `zstormetadata` field of `fileblock`. 

https://github.com/zero-os/0-metadata/blob/a8b6a78224b2836f18a85d562d1f6620287d757b/api_spec/types_md.raml#L11-L14

Is it point to `metatypes.Metadata.Key`  https://godoc.org/github.com/zero-os/0-stor/client/metastor/metatypes#Metadata ? Because this is the only key i know that available from the API call.

and `data` field of `metadata`
https://github.com/zero-os/0-metadata/blob/a8b6a78224b2836f18a85d562d1f6620287d757b/api_spec/types_md.raml#L134-L137

Is it point to `metatypes.Metadata.Key`  https://godoc.org/github.com/zero-os/0-stor/client/metastor/metatypes#Metadata ?

**Comment by iwanbk** [comment]
We also have this https://github.com/zero-os/0-metadata/blob/master/chain.png, but the way `bdomain` and `bobject` form the chain still not clear from the RAML file

**Comment by zaibon** [comment]
@iwanbk regarding the ztstormetadata we can adapt the structure to fit our need. I don't think there is all the information we need currently in the raml spec. 
Can you propose what would be the required attributes to fully support 0-stor metadata ?

**Comment by iwanbk** [comment]
> Can you propose what would be the required attributes to fully support 0-stor metadata ?

After looking at 0-stor's metastor/db.DB interface https://godoc.org/github.com/zero-os/0-stor/client/metastor/db#DB and some of the code, we don't need any other attributes for 0-metadata to be used as 0-stor metadata,  because the DB interface use KV store interface

So, the only field we need is metadata.data
https://github.com/zero-os/0-metadata/blob/a8b6a78224b2836f18a85d562d1f6620287d757b/api_spec/types_md.raml#L128-L137
metadata.data is 0-stor metadata value in []byte format

we can also delete this field https://github.com/zero-os/0-metadata/blob/a8b6a78224b2836f18a85d562d1f6620287d757b/api_spec/types_md.raml#L11-L14

**Comment by lafont-e** [comment]
As I see it, the only thing we need to store as metadata for a file is the full path name and the object store that keeps it. Having multiple stores, even if 0-stor provides a unified API for a bunch of them, will have multiple and different metadata to deal with, and is no business for 0-metadata.
What fields/values define a 0-stor storage area is another thing, usually an url, but not sure if something more would be needed, as the need to have redundancy and reliability will affect how the url is defined.
So unless told otherwise, will use URL and file name as the only metadata we need to keep
