### ISSUE TITLE
Non recursive `dir` API?

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-metadata#19]
Do we really only want to support one level of dir?

I don't see we use recursive directory feature of go-raml

**Comment by zaibon** [comment]
No indeed. That was the first idea of implementation, but that was before we knew the raml spec where already created.

**Comment by iwanbk** [comment]
> No indeed. That was the first idea of implementation, but that was before we knew the raml spec where already created.

It is for go-raml question

> Do we really only want to support one level of dir?

To make sure, the answer is "No", right?

I can see we can support it by encoding the directory structure

**Comment by zaibon** [comment]
> Do we really only want to support one level of dir?

yes tha'ts the idea, it's all directory based.
